### ISSUE TITLE
getting an error using the .tmux.conf on ubuntu 20.04 

### ISSUE THREAD

**Issue by basuparth** [nicknisi/vim-workshop#11]
When I try to source the .tmux.conf file I get a error saying

.tmux.conf:74: usage: bind-key [-cnr] [-T key-table] key comman[0/0]
guments]

tmux just displays this and there is no other entry mode left at the terminal at that point

**Comment by nicknisi** [comment]
Try replacing lines 74-75 with the following

```conf
bind -T copy-mode-vi v send -X begin-selection
```

**Comment by basuparth** [comment]
Doesn't work. on changing the lines when I execute tmux on my terminal I get [exited] followed by 65;1;9c

**Comment by nicknisi** [comment]
Hmm, this file is for an earlier version of tmux. I can look into it but in the mean time I would recommend checking out my current config in [my dotfiles](https://github.com/nicknisi/dotfiles/blob/master/tmux/tmux.conf.symlink).

**Comment by basuparth** [comment]
Thanks @nicknisi this works.
