### ISSUE TITLE
which key is this?

### ISSUE THREAD

**Issue by ilaipi** [nicknisi/vim-workshop#3]
![image](https://cloud.githubusercontent.com/assets/1689135/16830294/928f28cc-49d0-11e6-8c09-58aad53fb6e9.png)

I saw this when I watch your video on youtube, I wonder which key it is on keyboard?

**Comment by ilaipi** [comment]
I think it's `ESC`.

**Comment by nicknisi** [comment]
@ilaipi Yeah, it's `ESC`.
