### ISSUE TITLE
Terrible mistake

### ISSUE THREAD

**Issue by kholbekj** [nicknisi/vim-workshop#9]
On page 19 of the pdf, you put h j k l and write under it 'left up down right'. Should be 'left down up right'.

You may have been a driving factor in making me a vim/tmux user, I may use a crippled fork of your dotfiles, but I this cruel joke on newcomers should be rectified!

<3

**Comment by nicknisi** [comment]
Thanks. I fixed in the markdown source file, but don't currently have a way to rebuild the pdf as some of the underlying images are no longer available. I'm going to end up archiving this project as I don't really update it, and am working on an updated presentation/video. Thanks!
